import { ReactFlowProvider } from "reactflow";
import "./globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import Navbar from "./(components)/Navbar/Navbar";
import Footer from "./(components)/Footer/Footer";
import Providers from "@/redux/Providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <UserProvider>
          <body>
            <Navbar />
            {children}
            <Footer />
          </body>
        </UserProvider>
      </Providers>
    </html>
  );
}
